### ISSUE TITLE
Explore the KerbinSide hangars integration possibility

### ISSUE THREAD

**Issue by allista** [allista/hangar#124]

**Comment by allista** [comment]
It seems Kerbal Constructs has all the hangar possibilities in place already.

**Comment by Eskandare** [comment]
Yes it does but unfortunately needs some rewriting. limited to 3 crafts and 25 tons.

**Comment by allista** [comment]
Well, feel free to use AT_Utils and Hangar code if you need.

**Comment by allista** [comment]
Or maybe I myself could help with something?
