### ISSUE TITLE
Tanks not keeping their adjusted volume

### ISSUE THREAD

**Issue by Thorbane** [allista/hangar#165]
The configurable tanks revert to their default volume when the editor is reloaded, ignoring the changes in size made to the previously.

**Comment by allista** [comment]
You mean the "Revert to Editor" from flight?

*I'm starting to think that the whole tank's architecture is flawed =\

**Comment by allista** [comment]
And I can't reproduce it.
Could you write a step-by-step instruction?

**Comment by Thorbane** [comment]
If I quit the game, come back, and load the craft file in the editor, I see a 117 m^3 (the volume of the tank before any size changes) volume on a tank the should have about 217.

**Comment by Thorbane** [comment]
OK it works fine, unless the tank has some unassigned space in it, in which case the unassigned space gets deleted.
Make a craft with a tank that's had it's size increased, assign 1/2 of it to a resource, save the craft and press new craft.  Then reload the craft and compare the tank volume to what it should be.

**Comment by allista** [comment]
Thanks, that helped!
