### ISSUE TITLE
Toolbar wrapper needs updating

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [allista/hangar#171]
Due to changes in KSP 1.2 and Contract Configurator, any mod that integrates with Blizzy's Toolbar needs to make a minor update to the toolbar wrapper class (or else throw NotSupportedExceptions).  See blizzy78/ksp_toolbar#39 and blizzy78/ksp_toolbar@141485a715d11ac3d15d8d6f0ffafe5a01d853ba.  I'd make a pull request with this change, but I've run into difficulties in compiling Hangar's labyrinth of dependencies, so I haven't verified that it actually works (but it has for all the other mods that I've patched this way and have compiled and tested).

**Comment by allista** [comment]
Thanks a lot!

**Comment by allista** [comment]
The same should go for TCA.
I think it'll be easier if I just do it myself then.
