### ISSUE TITLE
Enhancement allow selectable launch positions

### ISSUE THREAD

**Issue by SpannerMonkey** [allista/hangar#173]
I use the hangar modules in the Large Boat Parts mod,  with one exception space is limited, and even in that one exception the fixed launch position is causing problems in testing. The problem being is that due to the varied craft likely to be carried, there is no one launch position that suits all situations. likely transportees  being very different dimensions above and below the mid point 

  To mitigate this somewhat i have placed extra named transforms in the hangar, 3 in most cases, and the facility to adjust them in cfg, while not wildly user friendly it does allow some customization for individual scenarios.  
  So i propose an added option to choose between a small selection of launch positions. as default eg your parts, it would show the normal position, ( although, it's likely an enhancement that would benefit your mod also) and other for mods would list additional possible transforms as they are added, perhaps a maximum of 4 extra, as that seems to be able to cover any clearance issues I've encountered in testing. for simplicity i followed your guide and adopted the accepted transform names , launch_position, launch_positionA. launch_positionB etc

The mod already performs very well and this would for me be the icing on the cake.

**Comment by allista** [comment]
If I understand correctly there's no really the need for this if you're using SpawnOffset.
Suggest to close the issue.
