### ISSUE TITLE
Compatibility issue with TweakScale?

### ISSUE THREAD

**Issue by m9731526** [allista/hangar#175]
If I try to select this in Fairing Hangar, then ksp will instantly crash.
[MiningStation.zip](https://github.com/allista/hangar/files/547133/MiningStation.zip)

I'm not sure this is a problem of TweakScale or a compatibility issue, just post it for that maybe you'll want to check it out. (Also confirmed that this crash happens with or without solar panel on the craft.)

>[TweakScale Warning] No valid member found for panelMass in ModuleDeployableSolarPanel
> TweakScale.Tools:LogWf(String, Object[])
> TweakScale.MemberUpdater:Create(Object, String)
> TweakScale.ScaleExponents:UpdateFields(Object, Object, ScalingFactor, Part)
> TweakScale.ScaleExponents:UpdateObject(Part, Part, Dictionary`2, ScalingFactor)
> TweakScale.TSGenericUpdater:OnRescale(ScalingFactor)
> TweakScale.TweakScale:CallUpdaters()
> TweakScale.TweakScale:Setup()
> TweakScale.TweakScale:OnLoad(ConfigNode)
> PartModule:Load(ConfigNode)
> Part:LoadModule(ConfigNode, Int32&)
> ShipConstruct:LoadShip(ConfigNode)
> AtHangar.PackedConstruct:LoadConstruct()
> AtHangar.PackedConstruct:.ctor(String, String)
> AtHangar.HangarMachinery:vessel_selected(String, LoadType)
> KSP.UI.Screens.CraftBrowserDialog:onPipelineFinished(ConfigNode, CraftEntry, LoadType)
> KSP.UI.Screens.<pipeSelectedItem>c__AnonStorey1AF:<>m__88D(ConfigNode)
> KSPUpgradePipeline:Process(ConfigNode, String, LoadContext, Callback`1, Callback`2)
> KSP.UI.Screens.CraftBrowserDialog:pipeSelectedItem(CraftEntry, LoadType)
> KSP.UI.Screens.CraftBrowserDialog:OnEntrySelected(CraftEntry)
> KSP.UI.Screens.CraftEntry:onValueChanged(Boolean)
> UnityEngine.Events.InvokableCall`1:Invoke(Object[])
> UnityEngine.Events.InvokableCallList:Invoke(Object[])
> UnityEngine.Events.UnityEventBase:Invoke(Object[])
> UnityEngine.Events.UnityEvent`1:Invoke(Boolean)
> UnityEngine.UI.Toggle:Set(Boolean, Boolean)
> UnityEngine.UI.Toggle:Set(Boolean)
> UnityEngine.UI.Toggle:set_isOn(Boolean)
> UnityEngine.UI.Toggle:InternalToggle()
> UnityEngine.UI.Toggle:OnPointerClick(PointerEventData)
> UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
> UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
> UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
> UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
> UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
> UnityEngine.EventSystems.StandaloneInputModule:Process()
> UnityEngine.EventSystems.EventSystem:Update()

**Comment by allista** [comment]
Thanks for the report. I'll look into it.

**Comment by m9731526** [comment]
It's actually much like a compatibility issue with EL mod, since I found that it will crash only when EL part is selected in Fairing Hangar (only Fairing Hangar).

**Comment by allista** [comment]
I had several crashes when launching Fairing Hangar with this station from editor to launchpad. But all of them were due to memory shortage (i'm on 32bit system). Other than that, it launches well on Kerbin and in orbit.
Then again, I tested this after I've fixed the #172  issue.

**Comment by allista** [comment]
Oh, and the TweakScale log has definitely nothing to do with this all.

**Comment by allista** [comment]
The new version with the fix is out. Please, test it and close the issue if it's gone.
