### ISSUE TITLE
Mass calculation broken with rover wheels and physics-less parts

### ISSUE THREAD

**Issue by andrewcchen** [allista/hangar#176]
![screenshot](https://cloud.githubusercontent.com/assets/6744506/21465195/9d387e74-c9fd-11e6-8618-774a5794a74a.png)

This craft's mass should be 565kg as shown by both KER and stock, but the hanger mod only calculates it to be 0.13t (rounded from 125kg), only taking into account the mass of the grider segment, but not the rover wheels nor the physics-less barometer.

This results in crafts having a lower mass than they should when put into a fairing hanger (and presumable others although I haven't tested with them).

**Comment by andrewcchen** [comment]
Since 1.0 I think physics-less parts have their mass added to their parent part, so they should not [be ignored](https://github.com/allista/AT_Utils/blob/master/Metric.cs#L125).

**Comment by allista** [comment]
Thank you for the report!
Will publish a fix in the next release.

**Comment by allista** [comment]
Fixed upstream in AT_Utils.
