### ISSUE TITLE
Fairing hanger becomes much heavier after payload have been jettisoned

### ISSUE THREAD

**Issue by andrewcchen** [allista/hangar#177]
Before jettison:
![screenshot1](https://cloud.githubusercontent.com/assets/6744506/21469008/68deed16-ca98-11e6-9cc8-f13594d4ac19.png)

After jettison:
![screenshot2](https://cloud.githubusercontent.com/assets/6744506/21469009/6cd2fe12-ca98-11e6-9f8a-f22fb482b1f9.png)

Instead of becoming lighter because the payload and faring have be jettisoned, the remaining fairing base becomes heavier.

**Comment by allista** [comment]
Thanks for the report, I'll look into it.

**Comment by allista** [comment]
Yep, I see it in the code. Will publish a fix with the next release. Thanks again.
