### ISSUE TITLE
KSP locks up when I try to relaunch a stored vessel that had a crew

### ISSUE THREAD

**Issue by Atario** [allista/hangar#192]
Steps:

1.  Have vessel A in orbit with crew
1.  Have vessel B in orbit with the Inline Hangar (no idea if this applies to other hangars or not) and enough crew space to take the other vessel's crew
1.  Fly A into B as usual
1.  Relaunch A from B

Result:  Vessel appears to spawn, but before the UI can be redrawn, KSP stops responding — frozen, with high CPU usage.  All other activity (disk, handles, swap, etc.) tails off to nothing.  KSP must be killed to recover.

Log attached:  [output_log.txt](https://github.com/allista/hangar/files/1445495/output_log.txt)

**Comment by allista** [comment]
Thanks for the report. I can reproduce it even with 1.3.1. Too bad.

**Comment by allista** [comment]
Fixed in 3.3.3
