### ISSUE TITLE
Squad stock cargo containers not closing to locked position

### ISSUE THREAD

**Issue by BararQ** [allista/hangar#194]
When closing a squad cargo hold, status on hangers show as
Status : Moving...
But will never get to locked position, this makes any items stored inside open to drag as if the cargo bay was open. I can remove the GameData\Hangar\MM\Squad.cfg file and it will get to a locked position when closing the bay. Items inside being protected from drag now. Not sure if this is intentional as it may be expected to use the hangar instead of placing items in the cargo hold. Also I did not put anything in the hangar or place items physically in the cargo hold during testing expect during a flight test to check for drag on items.

This affects the mk2CargoBayL, mk2CargoBayS, mk3CargoBayL, mk3CargoBayM, mk3CargoBayS from stock squad parts or all parts listed in the Squad.cfg

Current Mod list.
KSP 1.3.1 64Bit
Installed from CKAN
Mod Manager 2.8.1
AT Utils V1.5.0
Community Category Kit 2.0.2.0
Community Resource Pack 0.8.0.0
Configurable Containers Core 2.4.1.2
Firespitter Core v7.6.0
Hangar 3.3.3
KIS 1.8
KSP AVC 1.1.6.1

**Comment by allista** [comment]
Was unable to reproduce this on 1.4.1
I don't even see the "Status: ...." part menu item.
![screenshot1](https://user-images.githubusercontent.com/6084589/37920516-b6b40da6-312f-11e8-8715-3d74417d59ff.png)
