### ISSUE TITLE
Hangars cap at ~28% used volume

### ISSUE THREAD

**Issue by Darinth** [allista/hangar#196]
KSP Version 1.4.2
Hangars Version: 3.3.4

I'm not certain if I'm misunderstanding or if things are currently bugged, but the hangars stop being willing to store stuff at about 28% used volume which doesn't seem correct.

Probe:
![image](https://user-images.githubusercontent.com/4502486/38899858-4b1a4954-4267-11e8-8268-bf78e9fa0e81.png)

Hangar I'm trying to shove probes into:
![image](https://user-images.githubusercontent.com/4502486/38899639-8b6b3b68-4266-11e8-8c54-b4bae4be6215.png)

Probe is just a 100G relay, HECS2, 1K battery, FL-T100 Fuel tank, Terrier engine, a pair of hinge pivotrons with gigantor solar arrays. Problem presists even if I remove the pivotrons and has been a problem every time I've gone to use the hangars. Thus far my solution has been to simply staple probes onto the sides of crafts instead of using hangars... but I'd really like to be able to use them. They seem like a really cool concept and a good way to save on my part counts when I start getting into bigger ships. Is this the intended functionality or am I encountering a bug of some kind?

**Comment by Darinth** [comment]
A little bit of fiddling and I was able to get it well over my 28%, but still not even 50%.

**Comment by allista** [comment]
That's no bug, that's honesty =)
The used volume percentage is calculated directly as the volume of the convex hull of the stored vessel divided by the volume of the inner space (as defined by invisible mesh that closely repeats the visible inner walls).
So what you see (28% of inner space used) means that if you _liquify_ the red diamond (convex hull) from the screenshot it will fill just below the third of the hexagonal prism of the hangar. The remaining volume is the space you see around the diamond. It always seems counterintuitive, but remember that volume grows as a cube of linear dimensions.

**Comment by Darinth** [comment]
I suspected that may have been the case, especially given some of the further testing I did on the hangars. It's unfortunately frustrating without sufficient feedback on how the storage mechanics work. And honestly frustrating even given that I'm reasonably certain I understand them now. It appears as though the mod actually physically, though positioning of the vessels, attempts to fit all of the ships inside of the confines of the hangar and then simply reports back on the used volume after it's attempts to position the ships.

Is there any chance of convincing you to make a config option which simply calculates the volume of objects and then treats them as a liquid for storage purposes? While I understand and agree that the method you're using is more physically accurate, for me personally at least I feel like it results in most of the hangar functionality being all-but unusable.

Btw, I can take no for an answer. While I'm willing to ask modders if they're willing to make modifications, I'm well aware that you guys are spending your free time and that I've got no right to make demands. :)

**Comment by allista** [comment]
> It appears as though the mod actually physically, though positioning of the vessels, attempts to fit all of the ships inside of the confines of the hangar and then simply reports back on the used volume after it's attempts to position the ships.

That's exactly what happens. The most non-physical part is that ships are actually repacked each time a new one is added to use more free space. The algorithm used is bin-tree packaging.

The option you're asking is actually implemented, for there were several requests on the forum in the early days, when there were no rendering of hangar's content. To disable packing you need to create a text file `GameData/Hangar/Hangar.user` and add an override for global option there: `EnableVesselPacking = false`
