### ISSUE TITLE
KSP AVC report Compatibility issues about KSP version

### ISSUE THREAD

**Issue by Brettdah** [allista/hangar#204]
"The currently installed version of Hangar was built to run KSP 1.6.1 - 1.7.2" with KSP Steam version 1.7.3.2594.
Can you update the mod for the "new" version ?
I think there is no real compatibility issue here, right ?
thanks

**Comment by StoneBlue** [comment]
I certainly cant speak for Allista, but yes, I would most likely guess that there are no issues with  any of Allista's mods that say 1.7.2, being used in 1.7.3 with no issues.
Looks like Allista released most stuff for 1.7.2, and a week or two later 1.7.3 dropped, and most likely no changes were needed to the mods, and its not worth the time of repackaging and re-releasing everything solely for a version file update.
This happens with many mods.
its usually a good idea to check the last page of each mods' thread to see if a mod is still compatable with current KSP versions, as most likely, others have already asked the same question, and if there *are* issues, most likely they will have already been noted or discussed.
