### ISSUE TITLE
No edit contents option on RMB menu

### ISSUE THREAD

**Issue by davedev** [allista/hangar#218]
First let me say, I'm messing around in 1.10 with lots of mods and I fully understand this may be caused by another mod or 1.10 incompatibility.

In the release build, 3.6.0, I began having a problem where I could click edit contents and the load menu would appear - I could browse available craft to load but, clicking the load button did nothing.  A general null exception is shown in the console each time load is clicked.

I saw there were 6 commits since that build, including compatibility update in the version file for 1.10 so, I installed the current master and started a new, sandbox game.  The hangar parts no longer have the "edit contents" button.  Screenshots and logs are below.  

Lmk if you need me to test this on a fresh install to reproduce.  I don't have the time right now or I'd dive into this a little more on my side.

Screenshot: [https://1drv.ms/u/s!AtC9nbX8Ht1DnoVYmMfAjLeayDSIAA?e=3r13T4](url)
Logs: [https://1drv.ms/u/s!AtC9nbX8Ht1DnoVcxejfMGNgR_Zh5A?e=0vUmHM](url)

**Comment by allista** [comment]
Thanks for the report, I'll look into it.

**Comment by Monniasza** [comment]
@allista Release this update ASAP because this bug is mod-breaking.
