### ISSUE TITLE
Check hangar-rover friction problem

### ISSUE THREAD

**Issue by allista** [allista/hangar#69]
@AccidentalDisassembly claims it's still there in v1.1.1.1
http://forum.kerbalspaceprogram.com/threads/88933-0-24-2-Hangar-v1-1-1-1?p=1406314&viewfull=1#post1406314

**Comment by Thorbane** [comment]
I'm seeing it on the rover lander, haven't tried the ground hangars.

**Comment by allista** [comment]
I'm seeing it too, but after days of tests and debugging I still have no idea whatsoever of why the problem exists in the first place, let alone why the workaround does not work.

My most recent hypothesis is that the prime cause is the Unity itself and the old version of PhysX it uses. It treats collisions with mesh colliders of static and non-static objects differently; and collision with a non-static mesh collider causes two colliders to bounce continuously which effectively cancels out the friction. Combined with the new CollisionEnhancer in KSP 0.90 it kills my workaround.
Kerbals that try to walk on a surface of a lying part are also affected: they appear to be constantly falling.

**Comment by allista** [comment]
Fixed in 1.2
